apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-test
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/backstage-app
    repoURL: https://github.com/chess-seventh/assignment-fpiva-consensys
    targetRevision: HEAD
