apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: fullnameOverride
          value: kps
        - name: nameOverride
          value: kps
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
