apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-success-rate
spec:
  metrics:
    - name: success-rate
      initialDelay: 60s
      interval: 20s
      successCondition: result[0] < 4.5
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring:9090
          query: >+
            100 * (sum(rate(container_cpu_usage_seconds_total{pod=~"backstage-rollout.*"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{pod=~"backstage-rollout.*", resource="cpu"}) by (pod))
